"""
Base Agent class for all trading agents
"""
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional
import uuid


class AgentRole(Enum):
    """Agent roles in the trading system"""
    MARKET_ANALYST = "market_analyst"
    TECHNICAL_ANALYST = "technical_analyst"
    FUNDAMENTAL_ANALYST = "fundamental_analyst"
    SENTIMENT_ANALYST = "sentiment_analyst"
    RISK_MANAGER = "risk_manager"
    TRADER = "trader"
    PORTFOLIO_MANAGER = "portfolio_manager"
    NEWS_ANALYST = "news_analyst"


@dataclass
class AgentMessage:
    """Message structure for agent communication"""
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    sender: str = ""
    receiver: str = ""
    content: Dict[str, Any] = field(default_factory=dict)
    message_type: str = "analysis"
    timestamp: datetime = field(default_factory=datetime.utcnow)
    priority: int = 1  # 1-5, higher is more urgent

    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "sender": self.sender,
            "receiver": self.receiver,
            "content": self.content,
            "message_type": self.message_type,
            "timestamp": self.timestamp.isoformat(),
            "priority": self.priority
        }


@dataclass
class TradingSignal:
    """Trading signal generated by agents"""
    instrument: str
    direction: str  # "BUY", "SELL", "HOLD"
    confidence: float  # 0.0 to 1.0
    entry_price: Optional[float] = None
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    position_size: Optional[float] = None
    reasoning: str = ""
    timestamp: datetime = field(default_factory=datetime.utcnow)
    source_agent: str = ""


class BaseAgent(ABC):
    """
    Abstract base class for all trading agents.
    Each agent specializes in a specific aspect of trading analysis or execution.
    """

    def __init__(
        self,
        name: str,
        role: AgentRole,
        description: str = "",
        llm_client: Any = None
    ):
        self.id = str(uuid.uuid4())
        self.name = name
        self.role = role
        self.description = description
        self.llm_client = llm_client
        self.memory: List[AgentMessage] = []
        self.state: Dict[str, Any] = {}
        self.is_active = True

    @abstractmethod
    async def analyze(self, data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Perform analysis on the provided data.
        Must be implemented by each specialized agent.
        """
        pass

    @abstractmethod
    async def process_message(self, message: AgentMessage) -> Optional[AgentMessage]:
        """
        Process incoming message from another agent.
        Returns a response message or None.
        """
        pass

    @abstractmethod
    def get_system_prompt(self) -> str:
        """
        Return the system prompt for this agent's LLM interactions.
        """
        pass

    async def send_message(
        self,
        receiver: str,
        content: Dict[str, Any],
        message_type: str = "analysis",
        priority: int = 1
    ) -> AgentMessage:
        """Create and return a message to be sent to another agent."""
        message = AgentMessage(
            sender=self.name,
            receiver=receiver,
            content=content,
            message_type=message_type,
            priority=priority
        )
        self.memory.append(message)
        return message

    def update_state(self, key: str, value: Any) -> None:
        """Update agent's internal state."""
        self.state[key] = value

    def get_state(self, key: str, default: Any = None) -> Any:
        """Get value from agent's state."""
        return self.state.get(key, default)

    def clear_memory(self) -> None:
        """Clear agent's message memory."""
        self.memory = []

    def get_recent_memory(self, n: int = 10) -> List[AgentMessage]:
        """Get n most recent messages from memory."""
        return self.memory[-n:] if len(self.memory) >= n else self.memory

    def to_dict(self) -> Dict[str, Any]:
        """Serialize agent to dictionary."""
        return {
            "id": self.id,
            "name": self.name,
            "role": self.role.value,
            "description": self.description,
            "is_active": self.is_active,
            "state": self.state,
            "memory_size": len(self.memory)
        }

    def __repr__(self) -> str:
        return f"{self.__class__.__name__}(name={self.name}, role={self.role.value})"
